<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'knpu_lorem_ipsum.ipsum_api_controller' shared autowired service.

$this->services['knpu_lorem_ipsum.ipsum_api_controller'] = $instance = new \KnpU\LoremIpsumBundle\Controller\IpsumApiController(($this->services['knpu_lorem_ipsum.knpu_ipsum'] ?? $this->load('getKnpuLoremIpsum_KnpuIpsumService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));

$instance->setContainer((new \Symfony\Component\DependencyInjection\ServiceLocator(array('http_kernel' => function () {
    return ($this->services['http_kernel'] ?? $this->getHttpKernelService());
}, 'parameter_bag' => function () {
    return ($this->privates['parameter_bag'] ?? $this->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($this));
}, 'request_stack' => function () {
    return ($this->services['request_stack'] ?? $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack());
}, 'router' => function () {
    return ($this->services['router'] ?? $this->getRouterService());
})))->withContext('knpu_lorem_ipsum.ipsum_api_controller', $this));

return $instance;
